var f=document.getElementById('searchForm'), inp=document.getElementById('searchInput'), sp=document.getElementById('logoSpan'), ft=document.getElementById('footerText'), btns=document.querySelectorAll('.engine-btn'), grid=document.getElementById('bookmarksGrid'), mBtn=document.getElementById('toggleManageBtn');
var eng=localStorage.getItem('wn_engine')||'google', ed=false;
var def=[{name:'ВКонтакте',url:'https://vk.com',tag:'VK',color:'#0077FF'},{name:'GitHub',url:'https://github.com',tag:'GH',color:'#24292e'},{name:'4PDA',url:'https://4pda.to',tag:'4P',color:'#4CAF50'},{name:'YouTube',url:'https://youtube.com',tag:'YT',color:'#FF0000'}];
var bms=JSON.parse(localStorage.getItem('wn_bookmarks'))||def;
var cfg={google:{url:'https://google.com:'© WriskNuk Search. Поиск через Google.'},yandex:{url:'https://yandex.ru:'© WriskNuk Search. Поиск через Яндекс.'}};
function setEng(k){eng=k;localStorage.setItem('wn_engine',k);for(var i=0;i<btns.length;i++)btns[i].classList.toggle('active',btns[i].getAttribute('data-engine')===k);sp.style.color=k==='yandex'?'#000000':cfg[k].color;ft.textContent=cfg[k].txt;}
for(var i=0;i<btns.length;i++)btns[i].addEventListener('click',function(e){setEng(e.target.getAttribute('data-engine'));inp.focus();});
function render(){grid.innerHTML='';bms.forEach(function(b,idx){var c=document.createElement('div');c.className='bookmark-card'+(ed?' editing':'');c.addEventListener('click',function(){if(!ed)window.open(b.url,'_blank','noopener');});var ic=document.createElement('div');ic.className='bookmark-icon';ic.style.color=b.color;ic.textContent=b.tag;var lb=document.createElement('div');lb.className='bookmark-label';lb.textContent=b.name;var ov=document.createElement('div');ov.className='actions-overlay';var eB=document.createElement('button');eB.className='action-icon-btn edit';eB.setAttribute('data-index',idx);eB.textContent='✎';var dB=document.createElement('button');dB.className='action-icon-btn del';dB.setAttribute('data-index',idx);dB.textContent='✕';ov.appendChild(eB);ov.appendChild(dB);c.appendChild(ic);c.appendChild(lb);c.appendChild(ov);grid.appendChild(c);});var aC=document.createElement('div');aC.className='bookmark-card add-btn-card';var aI=document.createElement('div');aI.className='bookmark-icon';aI.textContent='+';var aL=document.createElement('div');aL.className='bookmark-label';aL.textContent='Добавить';aC.appendChild(aI);aC.appendChild(aL);aC.addEventListener('click',add);grid.appendChild(aC);}
mBtn.addEventListener('click',function(){ed=!ed;mBtn.textContent=ed?'Готово':'Изменить';render();});
grid.addEventListener('click',function(e){if(!ed)return;e.stopPropagation();var idx=e.target.getAttribute('data-index');if(idx===null)return;if(e.target.classList.contains('del')){bms.splice(idx,1);save();}else if(e.target.classList.contains('edit')){var b=bms[idx],n=prompt('Имя:',b.name),u=prompt('URL:',b.url);if(n&&u){b.name=n;b.url=u;b.tag=n.substring(0,2).toUpperCase();save();}}});
function add(){var n=prompt('Имя закладок:'),u=prompt('URL (с https://):');if(n&&u){var clr=['#0077FF','#24292e','#4CAF50','#FF0000','#9C27B0','#FF9800'];bms.push({name:n,url:u,tag:n.substring(0,2).toUpperCase(),color:clr[Math.floor(Math.random()*clr.length)]});save();}}
function save(){localStorage.setItem('wn_bookmarks',JSON.stringify(bms));render();}
f.addEventListener('submit',function(e){e.preventDefault();var q=inp.value.trim();if(q)window.location.href=cfg[eng].url+'?'+cfg[eng].param+'='+encodeURIComponent(q);});
setEng(eng);render();
